# Principal informations
name = "snt-chapter"
main = "index.js"
compatibility_date = "2026-08-26"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Static site
[assets]
directory = "./src/frontend"
binding = "ASSETS"

# Observability
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1