# Principal informations
name = "dashboard"
compatibility_date = "2026-08-26"

# Static site
[assets]
directory = "./"

# Observability
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1